services:
  migrate:
    image: migrate/migrate
    command: ["-path", "/migrations", "-database", "${DATABASE_URI}", "up"]
    volumes:
      - ./migrations:/migrations

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=${DATABASE_URI}
    depends_on:
      migrate:
        condition: service_completed_successfully
