apiVersion: apps/v1
kind: Deployment
metadata:
  name: youfood-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youfood-api
  template:
    metadata:
      labels:
        app: youfood-api
    spec:
      containers:
        - name: youfood-api
          image: docker.io/amiltoncabral/youfood-api:1.1
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-db
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-db
                  key: db_port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-db
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-db
                  key: db_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-db
                  key: db_name
---
apiVersion: v1
kind: Service
metadata:
  name: youfood-api
spec:
  type: LoadBalancer
  selector:
    app: youfood-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-db
type: Opaque
stringData:
  db_host: blfguy9v4iiyvznd0ogl-postgresql.services.clever-cloud.com
  db_port: "50013"
  db_user: urccm0eys3su8cm7fttp
  db_password:
  db_name: blfguy9v4iiyvznd0ogl
